(()=>{
  if(typeof game==='undefined')return;
  const VF=v=>{const s=String(v||'').toLowerCase();if(s.includes('sorcerer'))return 'Sorcerer';if(s.includes('druid'))return 'Druid';if(s.includes('paladin'))return 'Paladin';if(s.includes('knight'))return 'Knight';if(s.includes('monk'))return 'Monk';return '';};
  const SN={Knight:'Melee Fighting',Paladin:'Distance',Sorcerer:'Magic Level',Druid:'Magic Level',Monk:'Fist Fighting'};
  const SF={Knight:'melee',Paladin:'distance',Sorcerer:'magic',Druid:'magic',Monk:'fist'};
  function voc(){const m=typeof members!=='undefined'&&Array.isArray(members)?members.find(x=>x.name===game?.character):null;return VF(m?.vocation||'');}
  function ensure(){if(!game.skills||typeof game.skills!=='object')game.skills={};const v=voc()||'Knight',f=SF[v]||'melee';if(!Number.isFinite(Number(game.skills[f])))game.skills[f]=10;if(!Number.isFinite(Number(game.skills[f+'_progress'])))game.skills[f+'_progress']=0;return {v,field:f,value:Math.max(1,Math.floor(Number(game.skills[f])||1))};}
  function need(s){s=Math.max(1,Math.floor(Number(s)||1));return Math.max(40,Math.floor(80*Math.pow(1.06,Math.max(0,s-10))));}
  function progress(){const x=ensure();return Math.max(0,Number(game.skills[x.field+'_progress'])||0);}
  function train(n=1){const x=ensure();game.skills[x.field+'_progress']=progress()+n;while(game.skills[x.field+'_progress']>=need(x.value)){game.skills[x.field+'_progress']-=need(x.value);game.skills[x.field]++;x.value++;toast(`SKILL UP! ${SN[x.v]} ${x.value}.`);}if(typeof persist==='function')persist();render();}
  function bonus(){const x=ensure();return Math.max(0,x.value-10);}
  function installPanel(){if(document.getElementById('arenaSkills'))return;const shop=document.querySelector('.shop-section');if(!shop)return;const s=document.createElement('section');s.className='progress-section arena-skills-section';s.innerHTML='<div class="section-head"><div><div class="eyebrow">Treinamento</div><h2>Skills do personagem</h2></div></div><div id="arenaSkills"></div>';shop.parentNode.insertBefore(s,shop);const st=document.createElement('style');st.textContent='.arena-skills-section{margin-top:28px}.skill-card{background:rgba(15,15,20,.72);border:1px solid rgba(255,255,255,.08);border-radius:16px;padding:22px;max-width:760px}.skill-head{display:flex;justify-content:space-between;align-items:center;gap:16px}.skill-head h2{margin:4px 0 0}.skill-value{font-size:42px;font-weight:900}.skill-meta{display:flex;justify-content:space-between;margin:14px 0 10px;color:rgba(255,255,255,.72);font-size:13px}.skill-track{height:12px;border-radius:99px;background:rgba(255,255,255,.08);overflow:hidden}.skill-track i{display:block;height:100%;border-radius:99px;background:linear-gradient(90deg,#8b5cf6,#f59e0b);transition:width .3s ease}.skill-progress{margin-top:9px;font-size:13px;color:rgba(255,255,255,.72)}.skill-note{margin:12px 0 0;color:rgba(255,255,255,.55);font-size:12px;line-height:1.5}';document.head.appendChild(st);}
  function patch(){if(typeof startBattle==='function'&&!window.__arenaSkillBattlePatch){window.__arenaSkillBattlePatch=true;const old=startBattle;window.startBattle=function(...a){old(...a);if(battle)battle.attack+=bonus();};}if(typeof attack==='function'&&!window.__arenaSkillAttackPatch){window.__arenaSkillAttackPatch=true;const old=attack;window.attack=function(...a){if(!battle)return old(...a);const hp=battle.hp;const r=old(...a);if(hp>battle.hp)train(1);return r;};}}
  function render(){const b=document.getElementById('arenaSkills');if(!b)return;const x=ensure(),s=x.value,r=need(s),p=progress();b.innerHTML=`<div class="skill-card"><div class="skill-head"><div><div class="eyebrow">${SN[x.v]||'Combat Skill'}</div><h2>${x.v||'Aventureiro'}</h2></div><div class="skill-value">${s}</div></div><div class="skill-meta"><span>Skill atual</span><span>+${bonus()} dano</span></div><div class="skill-track"><i style="width:${Math.min(100,p/r*100)}%"></i></div><div class="skill-progress">${fmt(p)} / ${fmt(r)} para Skill ${s+1}</div><p class="skill-note">Inicialmente sobe rápido. Em skills altas, cada avanço exige progressivamente mais treinamento.</p></div>`;}
  window.arenaSkillBonus=bonus;window.arenaSkillTrain=train;window.arenaSkillRender=render;
  const nr=typeof normalizeGame==='function'?normalizeGame:null;if(nr&&!window.__arenaSkillNormalizePatch){window.__arenaSkillNormalizePatch=true;window.normalizeGame=function(){nr();ensure();};}
  const ra=typeof renderAll==='function'?renderAll:null;if(ra&&!window.__arenaSkillRenderPatch){window.__arenaSkillRenderPatch=true;window.renderAll=function(...a){const r=ra(...a);render();return r;};}
  installPanel();patch();ensure();render();
})();
