const API='https://api.tibiadata.com/v4/guild/'+encodeURIComponent('Mal Upados');
const STORAGE='malupados_arena_v1';
let members=[];
let game=null;
let battle=null;
const fmt=n=>new Intl.NumberFormat('pt-BR').format(Math.floor(Number(n)||0));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toISOString().slice(0,10);
const VOC_ICONS={Knight:'⚔',Paladin:'🏹',Sorcerer:'🔥',Druid:'❄️'};
const ZONES=[
 {id:'forest',name:'Floresta Sombria',icon:'🌲',min:1,color:'Fácil',monsters:[['Rat','🐀',35,22,12,20],['Troll','👹',55,38,20,35],['Orc','👺',72,55,28,50]]},
 {id:'orcs',name:'Acampamento Orc',icon:'🏕️',min:5,color:'Médio',monsters:[['Orc Berserker','👺',115,72,45,85],['Orc Rider','🐗',145,92,55,105],['Cyclops','👁️',175,110,70,135]]},
 {id:'desert',name:'Deserto Perdido',icon:'🏜️',min:12,color:'Difícil',monsters:[['Scorpion','🦂',230,128,90,170],['Ancient Scarab','🪲',280,155,110,210],['Dragon Hatchling','🐲',330,182,140,250]]},
 {id:'dragon',name:'Covil dos Dragões',icon:'🐉',min:20,color:'Muito difícil',monsters:[['Dragon','🐉',470,215,230,380],['Dragon Lord','🐲',620,275,340,520],['Frost Dragon','🐉',760,330,460,700]]},
 {id:'demon',name:'Abismo Demoníaco',icon:'😈',min:35,color:'Insano',monsters:[['Demon Skeleton','💀',980,395,650,900],['Hellhound','🐺',1250,485,820,1150],['Demon','😈',1600,600,1100,1600]]}
];
const WEAPONS=[['Espada de Bronze',0],['Fire Sword',8],['Heroic Axe',15],['Demon Blade',24],['Arcanum Edge',35]];
const ARMORS=[['Leather Armor',0],['Knight Armor',7],['Dragon Scale Mail',15],['Demon Armor',25],['Phoenix Plate',38]];
const CHALLENGES=[
 {type:'kills',label:'Caçador de hoje',desc:'Derrote 3 criaturas na Arena.',target:3,xp:90,gold:120},
 {type:'gold',label:'Caixa registradora',desc:'Ganhe 250 de ouro em batalhas.',target:250,xp:110,gold:150},
 {type:'wins',label:'Mais uma hunt',desc:'Vença 4 batalhas na Arena.',target:4,xp:130,gold:180},
 {type:'zone',label:'Explorador',desc:'Vença uma batalha na sua área mais avançada.',target:1,xp:160,gold:220}
];
function baseGame(name){return {character:name,level:1,xp:0,gold:100,wins:0,kills:0,damage:0,zone:0,weapon:0,armor:0,bestStreak:0,streak:0,lastChallenge:'',challengeProgress:0,challengeIndex:Math.floor(Math.random()*CHALLENGES.length)};}
function loadStore(){try{return JSON.parse(localStorage.getItem(STORAGE)||'{}')}catch{return {}}}
function saveStore(all){localStorage.setItem(STORAGE,JSON.stringify(all));game=all[game.character];}
function loadGame(name){let all=loadStore();if(!all[name])all[name]=baseGame(name);game=all[name];normalizeGame();saveStore(all)}
function normalizeGame(){game.level=Math.max(1,Number(game.level)||1);game.xp=Math.max(0,Number(game.xp)||0);game.gold=Math.max(0,Number(game.gold)||0);game.zone=Math.min(ZONES.length-1,Math.max(0,Number(game.zone)||0));game.weapon=Math.min(WEAPONS.length-1,Math.max(0,Number(game.weapon)||0));game.armor=Math.min(ARMORS.length-1,Math.max(0,Number(game.armor)||0));}
function persist(){let all=loadStore();all[game.character]=game;localStorage.setItem(STORAGE,JSON.stringify(all));}
function xpNeed(){return 100+((game.level-1)*65);}
function addXP(amount){let gained=0;game.xp+=amount;gained=amount;while(game.xp>=xpNeed()){game.xp-=xpNeed();game.level++;toast(`LEVEL UP! Você chegou ao Arena Level ${game.level}.`);}
 game.zone=Math.min(ZONES.length-1,Math.floor((game.level-1)/10));
 return gained;}
function toast(text){let old=document.querySelector('.toast');old?.remove();let el=document.createElement('div');el.className='toast';el.textContent=text;document.body.appendChild(el);setTimeout(()=>el.remove(),2600)}
function renderPlayer(){document.getElementById('playerName').textContent=game.character;document.getElementById('arenaLevel').textContent=fmt(game.level);document.getElementById('arenaXp').textContent=fmt(game.xp);document.getElementById('gold').textContent=fmt(game.gold);document.getElementById('wins').textContent=fmt(game.wins);document.getElementById('weapon').textContent=WEAPONS[game.weapon][0];document.getElementById('armor').textContent=ARMORS[game.armor][0];document.getElementById('avatar').textContent=VOC_ICONS[(members.find(m=>m.name===game.character)||{}).vocation]||'⚔';let need=xpNeed();document.getElementById('xpText').textContent=`${fmt(game.xp)} / ${fmt(need)}`;document.getElementById('xpBar').style.width=Math.min(100,game.xp/need*100)+'%';document.getElementById('classLine').textContent=(members.find(m=>m.name===game.character)||{}).vocation||'Aventureiro';}
function renderMap(){document.getElementById('map').innerHTML=ZONES.map((z,i)=>{let unlocked=game.level>=z.min;return `<button class="zone ${i===game.zone?'selected':''} ${unlocked?'':'locked'}" data-zone="${i}" ${unlocked?'':'disabled'}><span class="lock">${unlocked?'':'🔒 '+z.min}</span><div class="zone-icon">${z.icon}</div><strong>${esc(z.name)}</strong><small>${esc(z.color)} · Level ${z.min}+</small></button>`}).join('');document.querySelectorAll('.zone:not(.locked)').forEach(b=>b.onclick=()=>{game.zone=Number(b.dataset.zone);persist();renderAll();showZone(game.zone)});document.getElementById('zoneCount').textContent=`${game.zone+1} de ${ZONES.length} áreas desbloqueadas`;}
function showZone(index){if(battle)return;let z=ZONES[index];document.getElementById('battleArea').innerHTML=`<div class="battle-empty"><div class="battle-icon">${z.icon}</div><div class="battle-zone">${esc(z.name)}</div><h3>Escolha sua presa</h3><div class="monster-grid">${z.monsters.map((m,i)=>`<button class="monster-choice" data-monster="${i}"><span>${m[1]}</span><strong>${esc(m[0])}</strong><small>${m[2]} HP · +${m[4]} ouro</small></button>`).join('')}</div></div>`;document.querySelectorAll('.monster-choice').forEach(b=>b.onclick=()=>startBattle(index,Number(b.dataset.monster)))}
function startBattle(zoneIndex,monsterIndex){let m=ZONES[zoneIndex].monsters[monsterIndex];let bonus=WEAPONS[game.weapon][1],def=ARMORS[game.armor][1];battle={zoneIndex,monsterIndex,name:m[0],icon:m[1],maxHp:m[2]+game.level*8,hp:m[2]+game.level*8,damage:m[3]+Math.floor(game.level*1.7),gold:m[4]+game.level*3,xp:m[5]+game.level*12,playerHp:110+game.level*12+def*3,playerMax:110+game.level*12+def*3,attack:15+game.level*4+bonus*3,enemyDelay:0,log:[]};renderBattle();}
function battleLog(text){battle.log.unshift(text);battle.log=battle.log.slice(0,5)}
function attack(){if(!battle)return;let dmg=Math.max(1,battle.attack+Math.floor(Math.random()*12)-6);battle.hp=Math.max(0,battle.hp-dmg);game.damage+=dmg;battleLog(`Você causou <b>${dmg}</b> de dano.`);if(battle.hp<=0){winBattle();return}let incoming=Math.max(1,battle.damage+Math.floor(Math.random()*10)-5);battle.playerHp=Math.max(0,battle.playerHp-incoming);battleLog(`${esc(battle.name)} causou <b>${incoming}</b> de dano.`);if(battle.playerHp<=0){loseBattle();return}renderBattle()}
function winBattle(){let z=ZONES[battle.zoneIndex],m=ZONES[battle.zoneIndex].monsters[battle.monsterIndex];let streakBonus=Math.floor(game.streak/3)*15;let earnedXP=battle.xp+streakBonus,earnedGold=battle.gold;game.wins++;game.kills++;game.streak++;game.bestStreak=Math.max(game.bestStreak,game.streak);game.gold+=earnedGold;addXP(earnedXP);if(game.zone<battle.zoneIndex)game.zone=battle.zoneIndex;battleLog(`<span class="loot">VITÓRIA! +${fmt(earnedXP)} XP · +${fmt(earnedGold)} gold</span>`);persist();renderAll();document.getElementById('battleArea').innerHTML=`<div class="battle-empty result"><div class="battle-icon">🏆</div><div class="battle-zone">${esc(z.name)}</div><h3>${esc(m[0])} derrotado!</h3><p><strong class="loot">+${fmt(earnedXP)} XP</strong> &nbsp; <strong class="loot">+${fmt(earnedGold)} gold</strong></p><button class="btn active" id="againBtn">Escolher outra criatura</button></div>`;document.getElementById('againBtn').onclick=()=>showZone(game.zone);updateChallenge('wins',1);updateChallenge('kills',1);updateChallenge('gold',earnedGold);if(game.zone===battle.zoneIndex)updateChallenge('zone',1);battle=null;renderAll();}
function loseBattle(){game.streak=0;persist();battleLog('<b>Você foi derrotado.</b> A expedição termina aqui.');battle=null;renderAll();document.getElementById('battleArea').innerHTML=`<div class="battle-empty result"><div class="battle-icon">💀</div><h3>Você caiu.</h3><p>Seu ouro está seguro. Volte para tentar novamente.</p><button class="btn" id="retryBtn">Tentar novamente</button></div>`;document.getElementById('retryBtn').onclick=()=>showZone(game.zone)}
function renderBattle(){if(!battle)return;let pct=Math.max(0,battle.hp/battle.maxHp*100),ppct=Math.max(0,battle.playerHp/battle.playerMax*100);document.getElementById('battleArea').innerHTML=`<div class="battle-card"><div class="battle-head"><div><div class="battle-zone">${esc(ZONES[battle.zoneIndex].name)}</div><h3>${esc(battle.name)}</h3></div><button class="btn" id="fleeBtn">Fugir</button></div><div class="battle-enemies"><div class="fighter"><div class="fighter-icon">⚔️</div><h3>${esc(game.character)}</h3><div class="hp-track"><i style="width:${ppct}%"></i></div><div class="fighter-meta">HP ${fmt(battle.playerHp)} / ${fmt(battle.playerMax)}</div></div><div class="vs">VS</div><div class="fighter"><div class="fighter-icon">${battle.icon}</div><h3>${esc(battle.name)}</h3><div class="hp-track"><i style="width:${pct}%"></i></div><div class="fighter-meta">HP ${fmt(battle.hp)} / ${fmt(battle.maxHp)}</div></div></div><div class="battle-log">${battle.log.join('<br>')||'A criatura está olhando para você. Faça alguma coisa.'}</div><div class="battle-actions"><button class="btn active big" id="attackBtn">ATACAR</button></div></div>`;document.getElementById('attackBtn').onclick=attack;document.getElementById('fleeBtn').onclick=()=>{battle=null;showZone(game.zone)}}
function getChallenge(){let index=Math.abs(Number(game.challengeIndex)||0)%CHALLENGES.length;return CHALLENGES[index]}
function challengeValue(c){if(c.type==='wins')return game.wins; if(c.type==='gold'){let key=`malupados_challenge_gold_${today()}`;return Number(localStorage.getItem(key)||0)} if(c.type==='zone')return game.zone>0?1:0;return Number(localStorage.getItem(`malupados_challenge_kills_${today()}`)||0)}
function updateChallenge(type,value){let c=getChallenge();if(c.type!==type||game.lastChallenge===today())return;let key=type==='gold'?`malupados_challenge_gold_${today()}`:type==='kills'?`malupados_challenge_kills_${today()}`:null;if(key)localStorage.setItem(key,String(Number(localStorage.getItem(key)||0)+value));}
function renderChallenge(){let c=getChallenge(),done=game.lastChallenge===today(),value=Math.min(c.target,challengeValue(c));document.getElementById('dailyChallenge').innerHTML=`<div class="challenge-box ${done?'done':''}"><div class="challenge-title">${esc(c.label)}</div><div class="challenge-objective">${esc(c.desc)}</div><div class="challenge-reward">Recompensa: +${c.xp} XP · +${c.gold} gold</div><div class="challenge-progress">Progresso: ${fmt(value)} / ${fmt(c.target)}<span><i style="width:${Math.min(100,value/c.target*100)}%"></i></span></div></div>`;let btn=document.getElementById('challengeBtn');btn.disabled=done||value<c.target;btn.textContent=done?'Desafio concluído':value>=c.target?'Resgatar recompensa':'Conclua o desafio';document.getElementById('challengeStatus').textContent=done?'Recompensa já resgatada hoje.':'O desafio muda automaticamente a cada dia.'}
function claimChallenge(){let c=getChallenge(),v=Math.min(c.target,challengeValue(c));if(game.lastChallenge===today()||v<c.target)return;game.lastChallenge=today();game.gold+=c.gold;addXP(c.xp);persist();toast(`Desafio concluído! +${c.xp} XP e +${c.gold} gold.`);renderAll()}
const HUNT_POOL=['Exotic Cave','Carnivora’s Rock','Asura Palace','Werelions','Mirror Nightmare','Glooth Tower','Buried Cathedral','Issavi Surface','Summer Court','Deathlings','Dragon Lords','Roshamuul','Oramond West','Grimvale','Edron Vampire Crypt'];
function spin(){let btn=document.getElementById('spinBtn'),out=document.getElementById('rouletteResult');btn.disabled=true;out.classList.add('spinning');let n=0;let timer=setInterval(()=>{out.textContent=HUNT_POOL[Math.floor(Math.random()*HUNT_POOL.length)];n++;if(n>18){clearInterval(timer);let index=(game.level*13+game.wins*7+new Date().getDate())%HUNT_POOL.length;let result=HUNT_POOL[index];out.textContent=result;out.classList.remove('spinning');document.getElementById('rouletteMeta').textContent=`Boa sorte. Level ${game.level} · a Arena escolheu por você.`;btn.disabled=false}},70)}
function renderMilestones(){let list=[{l:1,t:'Aventureiro',d:'Entrou na Arena'},{l:5,t:'Caçador',d:'Acampamento Orc'},{l:12,t:'Explorador',d:'Deserto Perdido'},{l:20,t:'Matador de Dragões',d:'Covil dos Dragões'},{l:35,t:'Senhor do Abismo',d:'Abismo Demoníaco'}];document.getElementById('milestones').innerHTML=list.map(x=>`<div class="milestone ${game.level>=x.l?'unlocked':''}"><strong>${game.level>=x.l?'✓':'🔒'} ${esc(x.t)}</strong><span>Level ${x.l} · ${esc(x.d)}</span></div>`).join('')}
function renderRecords(){document.getElementById('records').innerHTML=`<div class="record"><span>Level máximo</span><strong>${fmt(game.level)}</strong></div><div class="record"><span>Melhor sequência</span><strong>${fmt(game.bestStreak)} vitórias</strong></div><div class="record"><span>Dano causado</span><strong>${fmt(game.damage)}</strong></div><div class="record"><span>Ouro guardado</span><strong>${fmt(game.gold)}</strong></div>`}
function renderAll(){normalizeGame();renderPlayer();renderMap();renderChallenge();renderMilestones();renderRecords();if(!battle)showZone(game.zone);}
async function load(){try{let r=await fetch(API+'?'+Date.now()),j=await r.json();members=j.guild?.members||[];members.sort((a,b)=>a.name.localeCompare(b.name));let select=document.getElementById('characterSelect');select.innerHTML=members.map(m=>`<option value="${esc(m.name)}">${esc(m.name)}</option>`).join('');if(!members.length)throw new Error('Sem membros');let store=loadStore();let saved=Object.keys(store)[0];let name=members.some(m=>m.name===saved)?saved:members[0].name;select.value=name;loadGame(name);select.onchange=()=>{battle=null;loadGame(select.value);renderAll()};renderAll()}catch(e){let fallback='Aventureiro';document.getElementById('characterSelect').innerHTML=`<option>${fallback}</option>`;loadGame(fallback);renderAll()}}
document.getElementById('spinBtn').onclick=spin;
document.getElementById('challengeBtn').onclick=claimChallenge;
document.getElementById('resetBtn').onclick=()=>{if(!confirm('Recomeçar este personagem na Arena? O progresso salvo neste navegador será apagado.'))return;let all=loadStore();all[game.character]=baseGame(game.character);localStorage.setItem(STORAGE,JSON.stringify(all));loadGame(game.character);battle=null;renderAll();toast('Personagem reiniciado.')};
load();
