const API='https://api.tibiadata.com/v4/guild/'+encodeURIComponent('Mal Upados');
const STORAGE='malupados_arena_v1';
let members=[];
let game=null;
let battle=null;
const fmt=n=>new Intl.NumberFormat('pt-BR').format(Math.floor(Number(n)||0));
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const VOC_ICONS={Knight:'⚔️',Paladin:'🏹',Sorcerer:'🔥',Druid:'❄️',Monk:'🖐️'};
const ZONES=[
 {id:'forest',name:'Floresta Sombria',icon:'🌲',min:1,color:'Fácil',monsters:[['Rat','🐀',35,22,12,20],['Troll','👹',55,38,20,35],['Orc','👺',72,55,28,50]]},
 {id:'orcs',name:'Acampamento Orc',icon:'🏕️',min:10,color:'Médio',monsters:[['Orc Berserker','👺',115,72,45,85],['Orc Rider','🐗',145,92,55,105],['Cyclops','👁️',175,110,70,135]]},
 {id:'desert',name:'Deserto Perdido',icon:'🏜️',min:20,color:'Difícil',monsters:[['Scorpion','🦂',230,128,90,170],['Ancient Scarab','🪲',280,155,110,210],['Dragon Hatchling','🐲',330,182,140,250]]},
 {id:'dragon',name:'Covil dos Dragões',icon:'🐉',min:35,color:'Muito difícil',monsters:[['Dragon','🐉',470,215,230,380],['Dragon Lord','🐲',620,275,340,520],['Frost Dragon','🐉',760,330,460,700]]},
 {id:'demon',name:'Abismo Demoníaco',icon:'😈',min:50,color:'Insano',monsters:[['Demon Skeleton','💀',980,395,650,900],['Hellhound','🐺',1250,485,820,1150],['Demon','😈',1600,600,1100,1600]]}
];
const WEAPONS=[['Espada de Bronze',0],['Fire Sword',8],['Heroic Axe',15],['Demon Blade',24],['Arcanum Edge',35]];
const ARMORS=[['Leather Armor',0],['Knight Armor',7],['Dragon Scale Mail',15],['Demon Armor',25],['Phoenix Plate',38]];
const CHALLENGES=[
 {type:'kills',label:'Caçador de hoje',desc:'Derrote 3 criaturas na Arena.',target:3,xp:900,gold:1200},
 {type:'gold',label:'Caixa registradora',desc:'Ganhe 250 de ouro em batalhas.',target:250,xp:1100,gold:1500},
 {type:'wins',label:'Mais uma hunt',desc:'Vença 4 batalhas na Arena.',target:4,xp:1300,gold:1800},
 {type:'zone',label:'Explorador',desc:'Vença uma batalha na sua área mais avançada.',target:1,xp:1600,gold:2200}
];
function baseGame(name){return {character:name,level:1,xp:0,gold:100,wins:0,kills:0,damage:0,zone:0,manualZone:0,weapon:0,armor:0,bestStreak:0,streak:0,lastChallenge:'',challengeProgress:0,challengeIndex:Math.floor(Math.random()*CHALLENGES.length),challengeDay:''};}
function loadStore(){try{return JSON.parse(localStorage.getItem(STORAGE)||'{}')}catch{return {}}}
function saveStore(all){localStorage.setItem(STORAGE,JSON.stringify(all));game=all[game.character];}
function loadGame(name){let all=loadStore();if(!all[name])all[name]=baseGame(name);game=all[name];try{const savedOutfit=localStorage.getItem('mage_outfit_config');if(savedOutfit)game.outfit=JSON.parse(savedOutfit)}catch(e){}normalizeGame();if(!Number.isInteger(game.manualZone))game.manualZone=game.zone;saveStore(all)}
function normalizeGame(){game.level=Math.max(1,Number(game.level)||1);game.xp=Math.max(0,Number(game.xp)||0);game.gold=Math.max(0,Number(game.gold)||0);game.zone=Math.min(ZONES.length-1,Math.max(0,Number(game.zone)||0));game.manualZone=Math.min(ZONES.length-1,Math.max(0,Number(game.manualZone??game.zone)||0));game.weapon=Math.min(WEAPONS.length-1,Math.max(0,Number(game.weapon)||0));game.armor=Math.min(ARMORS.length-1,Math.max(0,Number(game.armor)||0));}
function persist(){let all=loadStore();all[game.character]=game;localStorage.setItem(STORAGE,JSON.stringify(all));}
function xpNeed(){return 100+((game.level-1)*65);}
function addXP(amount){let gained=amount;game.xp+=amount;while(game.xp>=xpNeed()){game.xp-=xpNeed();game.level++;toast(`LEVEL UP! Você chegou ao Arena Level ${game.level}.`);}return gained;}
function toast(text){let old=document.querySelector('.toast');old?.remove();let el=document.createElement('div');el.className='toast';el.textContent=text;document.body.appendChild(el);setTimeout(()=>el.remove(),2600)}
function renderPlayer(){document.getElementById('playerName').textContent=game.character;document.getElementById('arenaLevel').textContent=fmt(game.level);document.getElementById('arenaXp').textContent=fmt(game.xp);document.getElementById('gold').textContent=fmt(game.gold);document.getElementById('wins').textContent=fmt(game.wins);document.getElementById('weapon').textContent=WEAPONS[game.weapon][0];document.getElementById('armor').textContent=ARMORS[game.armor][0];document.getElementById('avatar').textContent=VOC_ICONS[(members.find(m=>m.name===game.character)||{}).vocation]||'⚔';let need=xpNeed();document.getElementById('xpText').textContent=`${fmt(game.xp)} / ${fmt(need)}`;document.getElementById('xpBar').style.width=Math.min(100,game.xp/need*100)+'%';document.getElementById('classLine').textContent=(members.find(m=>m.name===game.character)||{}).vocation||'Aventureiro';}
function narrativeZoneRequirement(index){const req=[null,{event:'map1_fragment',label:'Conclua a lore da Floresta e derrote o Guardião.'},{event:'map2_gate_open',label:'Derrote o chefe Orc e abra o portão pela lore.'},{event:'map3_flashback',label:'Derrote o General da Magia e conclua o flashback.'},{event:'map4_descent',label:'Derrote o General das Feras e abra o caminho para o Abismo.'}][index];return req||null;}
function zoneUnlocked(index){if(!game||index<0||index>=ZONES.length)return false;if(game.level<ZONES[index].min)return false;if(index===0)return true;const n=window.ArenaNarrative;if(!n)return false;const req=narrativeZoneRequirement(index);return !!req&&n.hasEvent(req.event);}
function highestUnlockedZone(){let last=0;for(let i=1;i<ZONES.length;i++){if(zoneUnlocked(i))last=i;else break}return last;}
function renderMap(){document.getElementById('map').innerHTML=ZONES.map((z,i)=>{let levelOk=game.level>=z.min,progressOk=zoneUnlocked(i),unlocked=levelOk&&progressOk;let label=!levelOk?`🔒 ${z.min}`:unlocked?'':'🔒 BOSS + LORE';return `<button class="zone ${i===game.zone?'selected':''} ${unlocked?'':'locked'}" data-zone="${i}" ${unlocked?'':'disabled'}><span class="lock">${label}</span><div class="zone-icon">${z.icon}</div><strong>${esc(z.name)}</strong><small>${esc(z.color)} · ${unlocked?'Liberada':'Boss + lore necessários'}</small></button>`}).join('');document.querySelectorAll('.zone:not(.locked)').forEach(b=>b.onclick=()=>{game.manualZone=Number(b.dataset.zone);game.zone=game.manualZone;persist();renderAll();showZone(game.zone)});const unlockedCount=ZONES.filter((z,i)=>zoneUnlocked(i)).length;document.getElementById('zoneCount').textContent=`${unlockedCount} de ${ZONES.length} áreas desbloqueadas`;}
function showZone(index){if(battle)return;index=Math.min(ZONES.length-1,Math.max(0,Number(index)||0));if(!zoneUnlocked(index)){const req=narrativeZoneRequirement(index);if(typeof toast==='function'){const message=index>0&&!zoneUnlocked(index)?(req?.label||'Derrote o Boss e conclua a lore anterior.'):'Área bloqueada.';toast(message)}return;}game.zone=index;let z=ZONES[index];document.getElementById('battleArea').innerHTML=`<div class="battle-empty"><div class="battle-icon">${z.icon}</div><div class="battle-zone">${esc(z.name)}</div><h3>Escolha sua presa</h3><div class="monster-grid">${z.monsters.map((m,i)=>`<button class="monster-choice" data-monster="${i}"><span>${m[1]}</span><strong>${esc(m[0])}</strong><small>${m[2]} HP · +${m[4]} ouro</small></button>`).join('')}</div></div>`;document.querySelectorAll('.monster-choice').forEach(b=>b.onclick=()=>startBattle(index,Number(b.dataset.monster)))}
function startBattle(zoneIndex,monsterIndex){if(battle)return;zoneIndex=Math.min(ZONES.length-1,Math.max(0,Number(zoneIndex)||0));monsterIndex=Math.min(ZONES[zoneIndex].monsters.length-1,Math.max(0,Number(monsterIndex)||0));let m=ZONES[zoneIndex].monsters[monsterIndex];let bonus=WEAPONS[game.weapon][1],def=ARMORS[game.armor][1];battle={zoneIndex,monsterIndex,name:m[0],icon:m[1],maxHp:m[2]+game.level*8,hp:m[2]+game.level*8,damage:m[3]+Math.floor(game.level*1.7),gold:m[4]+game.level*3,xp:m[5]+game.level*12,playerHp:110+game.level*12+def*3,playerMax:110+game.level*12+def*3,attack:15+game.level*4+bonus*3,enemyDelay:0,log:[],busy:false};renderBattle();}
function battleLog(text){if(!battle)return;battle.log.unshift(text);battle.log=battle.log.slice(0,5)}
function attack(){if(!battle||battle.busy)return;battle.busy=true;let dmg=Math.max(1,battle.attack+Math.floor(Math.random()*12)-6);battle.hp=Math.max(0,battle.hp-dmg);game.damage+=dmg;battleLog(`Você causou <b>${dmg}</b> de dano.`);if(battle.hp<=0){if(battle.mirror){winMirrorBattle();return}winBattle();return}let incoming=Math.max(1,battle.damage+Math.floor(Math.random()*10)-5);battle.playerHp=Math.max(0,battle.playerHp-incoming);battleLog(`${esc(battle.name)} causou <b>${incoming}</b> de dano.`);if(battle.playerHp<=0){if(battle.mirror){loseMirrorBattle();return}loseBattle();return}battle.busy=false;renderBattle();if(battle?.mirror)window.ArenaMirrorMatch?.pulse()}
function winMirrorBattle(){if(!battle)return;battleLog('<span class="loot">KAELEN CAIU.</span>');persist();battle=null;window.dispatchEvent(new CustomEvent('arena:mirror-defeated',{detail:{character:game.character}}));}
function loseMirrorBattle(){if(!battle)return;game.streak=0;persist();battleLog('<b>Você caiu diante do seu próprio espelho.</b>');battle=null;renderAll();document.getElementById('battleArea').innerHTML='<div class="battle-empty result"><div class="battle-icon">☾</div><h3>O espelho venceu.</h3><p>A batalha não altera seu progresso de Arena. A história continua disponível após a revelação.</p><button class="btn" id="mirrorRetryBtn">Tentar novamente</button></div>';document.getElementById('mirrorRetryBtn').onclick=()=>window.ArenaMirrorMatch?.start();}
function startMirrorBattle(){if(battle)return false;const n=window.ArenaNarrative;if(!n?.hasEvent('finale_kaelen_reveal'))return false;let bonus=WEAPONS[game.weapon][1],def=ARMORS[game.armor][1],playerMax=110+game.level*12+def*3,attackPower=15+game.level*4+bonus*3;battle={mirror:true,name:'Kaelen',icon:'☾',maxHp:playerMax,hp:playerMax,damage:attackPower,playerHp:playerMax,playerMax,attack:attackPower,enemyDelay:0,log:['<b>Kaelen ergue a arma.</b> O mesmo ritmo. A mesma força.'],busy:false};renderBattle();return true;}
function winBattle(){if(!battle)return;let z=ZONES[battle.zoneIndex],m=ZONES[battle.zoneIndex].monsters[battle.monsterIndex],killedMonster=m[0];let streakBonus=Math.floor(game.streak/3)*15,earnedXP=battle.xp+streakBonus,earnedGold=battle.gold,wonZone=game.zone===battle.zoneIndex||battle.zoneIndex>game.zone;game.wins++;game.kills++;game.streak++;game.bestStreak=Math.max(game.bestStreak,game.streak);game.gold+=earnedGold;addXP(earnedXP);battleLog(`<span class="loot">VITÓRIA! +${fmt(earnedXP)} XP · +${fmt(earnedGold)} gold</span>`);updateChallenge('wins',1);updateChallenge('kills',1);updateChallenge('gold',earnedGold);if(wonZone)updateChallenge('zone',1);window.dispatchEvent(new CustomEvent('arena:bestiary-kill',{detail:{name:killedMonster,character:game.character}}));persist();battle=null;renderAll();document.getElementById('battleArea').innerHTML=`<div class="battle-empty result"><div class="battle-icon">🏆</div><div class="battle-zone">${esc(z.name)}</div><h3>${esc(m[0])} derrotado!</h3><p><strong class="loot">+${fmt(earnedXP)} XP</strong> &nbsp; <strong class="loot">+${fmt(earnedGold)} gold</strong></p><p>Escolha a próxima criatura:</p><div class="monster-grid">${z.monsters.map((x,i)=>`<button class="monster-choice" data-monster="${i}"><span>${x[1]}</span><strong>${esc(x[0])}</strong><small>${x[2]} HP · +${x[4]} ouro</small></button>`).join('')}</div></div>`;document.querySelectorAll('.monster-choice').forEach(b=>b.onclick=()=>startBattle(game.zone,Number(b.dataset.monster)));}
function loseBattle(){if(!battle)return;game.streak=0;persist();battleLog('<b>Você foi derrotado.</b> A expedição termina aqui.');battle=null;renderAll();document.getElementById('battleArea').innerHTML=`<div class="battle-empty result"><div class="battle-icon">💀</div><h3>Você caiu.</h3><p>Seu ouro está seguro. Volte para tentar novamente.</p><button class="btn" id="retryBtn">Tentar novamente</button></div>`;document.getElementById('retryBtn').onclick=()=>showZone(game.zone)}
function renderBattle(){if(!battle)return;let pct=Math.max(0,battle.hp/battle.maxHp*100),ppct=Math.max(0,battle.playerHp/battle.playerMax*100),mirror=!!battle.mirror;document.getElementById('battleArea').innerHTML=`<div class="battle-card ${mirror?'arena-mirror-battle':''}"><div class="battle-head"><div><div class="battle-zone">${mirror?'SALÃO DE CRISTAL':esc(ZONES[battle.zoneIndex].name)}</div><h3>${esc(battle.name)}</h3></div><button class="btn" id="fleeBtn" ${mirror?'disabled':''}>${mirror?'SEM FUGA':'Fugir'}</button></div><div class="battle-enemies"><div class="fighter"><div class="fighter-icon">⚔️</div><h3>${esc(game.character)}</h3><div class="hp-track"><i style="width:${ppct}%"></i></div><div class="fighter-meta">HP ${fmt(battle.playerHp)} / ${fmt(battle.playerMax)} · ATK ${fmt(battle.attack)}</div></div><div class="vs">VS</div><div class="fighter"><div class="fighter-icon">${battle.icon}</div><h3>${esc(battle.name)}</h3><div class="hp-track"><i style="width:${pct}%"></i></div><div class="fighter-meta">HP ${fmt(battle.hp)} / ${fmt(battle.maxHp)} · ATK ${fmt(battle.damage)}</div></div></div><div class="battle-log">${battle.log.join('<br>')||'A criatura está olhando para você. Faça alguma coisa.'}</div><div class="battle-actions"><button class="btn active big" id="attackBtn">ATACAR</button></div></div>`;document.getElementById('attackBtn').onclick=attack;document.getElementById('fleeBtn').onclick=()=>{if(battle?.mirror)return;battle=null;showZone(game.zone)}}
function challengeStorageKey(type){return `malupados_challenge_${encodeURIComponent(String(game?.character||'unknown'))}_${type}_${today()}`}
function dailyChallengeIndex(){const name=String(game?.character||'unknown'),date=today();let hash=0;for(let i=0;i<name.length;i++)hash=(hash*31+name.charCodeAt(i))>>>0;for(let i=0;i<date.length;i++)hash=(hash*17+date.charCodeAt(i))>>>0;return hash%CHALLENGES.length}
function getChallenge(){const day=today(),index=dailyChallengeIndex();if(game.challengeDay!==day||Number(game.challengeIndex)!==index){game.challengeDay=day;game.challengeIndex=index;game.challengeProgress=0;persist()}return CHALLENGES[index]}
function challengeValue(c){return Number(localStorage.getItem(challengeStorageKey(c.type))||0)}
function updateChallenge(type,value){let c=getChallenge();if(c.type!==type||game.lastChallenge===today())return;const key=challengeStorageKey(type);localStorage.setItem(key,String(Number(localStorage.getItem(key)||0)+value));}
function renderChallenge(){let c=getChallenge(),done=game.lastChallenge===today(),value=Math.min(c.target,challengeValue(c));document.getElementById('dailyChallenge').innerHTML=`<div class="challenge-box ${done?'done':''}"><div class="challenge-title">${esc(c.label)}</div><div class="challenge-objective">${esc(c.desc)}</div><div class="challenge-reward">Recompensa: +${c.xp} XP · +${c.gold} gold</div><div class="challenge-progress">Progresso: ${fmt(value)} / ${fmt(c.target)}<span><i style="width:${Math.min(100,value/c.target*100)}%"></i></span></div></div>`;let btn=document.getElementById('challengeBtn');btn.disabled=done||value<c.target;btn.textContent=done?'Desafio concluído':value>=c.target?'Resgatar recompensa':'Conclua o desafio';btn.onclick=claimChallenge;document.getElementById('challengeStatus').textContent=done?'Recompensa já resgatada hoje.':'O desafio muda automaticamente a cada dia.'}
function claimChallenge(){let c=getChallenge(),v=Math.min(c.target,challengeValue(c));if(game.lastChallenge===today()||v<c.target)return;game.lastChallenge=today();game.gold+=c.gold;addXP(c.xp);persist();toast(`Desafio concluído! +${c.xp} XP e +${c.gold} gold.`);renderAll()}
const HUNT_POOL=['Exotic Cave','Carnivora’s Rock','Asura Palace','Werelions','Mirror Nightmare','Glooth Tower','Buried Cathedral','Issavi Surface','Summer Court','Deathlings','Dragon Lords','Roshamuul','Oramond West','Grimvale','Edron Vampire Crypt'];
function spin(){let btn=document.getElementById('spinBtn'),out=document.getElementById('rouletteResult');if(!btn||!out)return;btn.disabled=true;out.classList.add('spinning');let n=0;let timer=setInterval(()=>{out.textContent=HUNT_POOL[Math.floor(Math.random()*HUNT_POOL.length)];n++;if(n>18){clearInterval(timer);let index=(game.level*13+game.wins*7+new Date().getDate())%HUNT_POOL.length;let result=HUNT_POOL[index];out.textContent=result;out.classList.remove('spinning');let meta=document.getElementById('rouletteMeta');if(meta)meta.textContent=`Boa sorte. Level ${game.level} · a Arena escolheu por você.`;btn.disabled=false}},70)}
function renderMilestones(){let list=[{l:1,t:'Aventureiro',d:'Entrou na Arena'},{l:10,t:'Caçador',d:'Acampamento Orc'},{l:20,t:'Explorador',d:'Deserto Perdido'},{l:35,t:'Matador de Dragões',d:'Covil dos Dragões'},{l:50,t:'Senhor do Abismo',d:'Abismo Demoníaco'}];document.getElementById('milestones').innerHTML=list.map(x=>`<div class="milestone ${game.level>=x.l?'unlocked':''}"><strong>${game.level>=x.l?'✓':'🔒'} ${esc(x.t)}</strong><span>Level ${x.l} · ${esc(x.d)}</span></div>`).join('')}
function renderRecords(){document.getElementById('records').innerHTML=`<div class="record"><strong>${fmt(game.wins)}</strong><span>Vitórias</span></div><div class="record"><strong>${fmt(game.kills)}</strong><span>Abates</span></div><div class="record"><strong>${fmt(game.gold)}</strong><span>Gold</span></div><div class="record"><strong>${fmt(game.damage)}</strong><span>Dano causado</span></div>`}
function renderAll(){if(!game)return;normalizeGame();const accessible=highestUnlockedZone();if(!zoneUnlocked(game.zone))game.zone=accessible;if(!zoneUnlocked(game.manualZone))game.manualZone=accessible;renderPlayer();renderMap();renderMilestones();renderRecords();renderChallenge();if(window.__arenaCharacterDraw)window.__arenaCharacterDraw();if(typeof renderShop==='function')renderShop();if(typeof renderProfileUI==='function')renderProfileUI();if(typeof renderBackpackUI==='function')renderBackpackUI();if(typeof renderMonkShopFix==='function')renderMonkShopFix();}
function load(){fetch(API).then(r=>r.json()).then(data=>{members=data.guild?.members||[];if(!members.length)throw new Error('Guilda sem membros');let stored=loadStore();let names=members.map(m=>m.name);let existing=Object.keys(stored).find(n=>names.includes(n));loadGame(existing||names[0]);renderAll();showZone(game.zone);}).catch(err=>{members=[{name:'Demo Knight',vocation:'Knight'}];let stored=loadStore();let existing=Object.keys(stored)[0];loadGame(existing||members[0].name);renderAll();showZone(game.zone)});}
async function bootArenaData(){for(let i=0;i<15&&!window.malUpadosSupabase;i++)await new Promise(r=>setTimeout(r,100));if(window.malUpadosSupabase?.auth){const {data:{user}}=await window.malUpadosSupabase.auth.getUser();if(user){for(let i=0;i<30&&!window.arenaSyncCharacters;i++)await new Promise(r=>setTimeout(r,100));if(window.arenaSyncCharacters){await window.arenaSyncCharacters();return;}}}await load();}
bootArenaData();
