const arenaProfileObserver=new MutationObserver(()=>{const modal=document.querySelector('.modal.open .modalbox');if(!modal||modal.querySelector('.profile-timeline'))return;const h=modal.querySelector('h2');if(!h)return;const name=h.textContent.trim(),ds=Object.keys(history||{}).sort(),pts=ds.map(d=>Number((history[d]||{})[name]||0)).filter(Boolean).slice(-30);if(pts.length<2)return;const wrap=document.createElement('div');wrap.className='panel profile-timeline';wrap.style.marginTop='12px';wrap.innerHTML='<strong>Gráfico de evolução</strong><svg viewBox="0 0 700 180" style="width:100%;height:auto;margin-top:10px"></svg><div class="small">Últimos '+pts.length+' snapshots registrados.</div>';modal.querySelector('.panel')?.before(wrap);const svg=wrap.querySelector('svg'),min=Math.min(...pts),max=Math.max(...pts),range=Math.max(1,max-min),line=pts.map((v,i)=>`${20+i/(pts.length-1)*650},${150-(v-min)/range*125}`).join(' ');svg.innerHTML=`<polyline points="${line}" fill="none" stroke="var(--red2)" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>${pts.map((v,i)=>`<circle cx="${20+i/(pts.length-1)*650}" cy="${150-(v-min)/range*125}" r="3" fill="var(--gold2)"><title>${fmt(v)} · ${ds.slice(-pts.length)[i]}</title></circle>`).join('')}`});arenaProfileObserver.observe(document.body,{childList:true,subtree:true});
function compareSeries(name,ds){let last=null;return ds.map(d=>{let v=Number((history[d]||{})[name]);if(v>0)last=v;return last==null?null:xp(last)}).filter(v=>v!=null)}
function drawCompare(){const c=document.getElementById('compareChart'),empty=document.getElementById('compareEmpty');if(!c)return;const ctx=c.getContext('2d'),rect=c.getBoundingClientRect(),dpr=window.devicePixelRatio||1,W=Math.max(600,rect.width),H=300;c.width=W*dpr;c.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,W,H);if(!selected||selected.length<2){empty.hidden=false;return}let ds=Object.keys(history||{}).sort();if(ds.length<2){empty.hidden=false;return}empty.hidden=true;const colors=['#d04b3e','#f0c45c','#70b77a','#8b79d9'];let series=selected.map(n=>({name:n,values:compareSeries(n,ds)}));let all=series.flatMap(s=>s.values);let min=Math.min(...all),max=Math.max(...all);if(!Number.isFinite(min)||!Number.isFinite(max)||min===max){empty.textContent='Os membros selecionados ainda não têm evolução diferente registrada.';empty.hidden=false;return}const pad={l:70,r:25,t:25,b:45},pw=W-pad.l-pad.r,ph=H-pad.t-pad.b;ctx.strokeStyle='#2b3037';ctx.lineWidth=1;for(let i=0;i<4;i++){let y=pad.t+i*ph/3;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(W-pad.r,y);ctx.stroke();ctx.fillStyle='#8d929a';ctx.font='11px Inter';let val=max-i*(max-min)/3;ctx.fillText((val/1000000).toFixed(1)+'M XP',5,y+4)}series.forEach((s,idx)=>{ctx.beginPath();s.values.forEach((v,i)=>{let x=pad.l+(i/Math.max(1,s.values.length-1))*pw,y=pad.t+(max-v)/(max-min)*ph;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle=colors[idx];ctx.lineWidth=3;ctx.stroke();ctx.fillStyle=colors[idx];ctx.font='12px Inter';ctx.fillText(s.name,10,16+idx*18)});ctx.strokeStyle='#2b3037';ctx.beginPath();ctx.moveTo(pad.l,pad.t);ctx.lineTo(pad.l,H-pad.b);ctx.lineTo(W-pad.r,H-pad.b);ctx.stroke();ctx.fillStyle='#8d929a';ctx.font='11px Inter';ds.forEach((d,i)=>{if(i===0||i===ds.length-1||i%Math.max(1,Math.floor(ds.length/6))===0){let x=pad.l+(i/Math.max(1,ds.length-1))*pw;ctx.fillText(d.slice(5),x-16,H-14)}})}
window.addEventListener('resize',drawCompare);

/* Base de hunts: faixa segura, objetivo, criaturas, requisitos e observações.
   Os spots são referências editoriais; a página não inventa uma XP/h fixa. */
const huntData={
Knight:[
{min:8,max:25,n:'Rotworms — Darashia/Liberty Bay',mon:'Rotworm, Carrion Worm',xp:'baixa',profit:'baixo',diff:1,goal:'safe',req:'Set básico + arma adequada',tip:'Puxe poucos por vez. Excelente para sair do começo sem tomar dano desnecessário.'},
{min:20,max:50,n:'Cyclops / Mount Sternum',mon:'Cyclops, Dwarf Soldier',xp:'baixa-média',profit:'baixo',diff:2,goal:'balance',req:'Shield decente e skills compatíveis',tip:'Boa transição para área aberta. Evite juntar muitos cyclops enquanto os skills ainda estiverem baixos.'},
{min:50,max:90,n:'Bog Raiders — Yalahar',mon:'Bog Raider',xp:'média-alta',profit:'médio',diff:3,goal:'balance',req:'Premium; imbuements ajudam',tip:'Um dos melhores degraus para EK nessa faixa. Controle o tamanho da pull e use sustain para manter a defesa estável.'},
{min:80,max:120,n:'Grimvale — -4',mon:'Werewolf, Werebear',xp:'média-alta',profit:'médio',diff:3,goal:'profit',req:'Acesso a Grimvale',tip:'Boa opção quando o objetivo é equilibrar XP e loot. Atenção às criaturas que podem quebrar sua defesa.'},
{min:100,max:160,n:'Oramond West — Minos',mon:'Minotaur Amazon, Execowtioner',xp:'alta',profit:'alto',diff:4,goal:'profit',req:'Acesso Oramond; set/imbues recomendados',tip:'Excelente para profit. Comece controlado e aumente a pull conforme conhecer o respawn.'},
{min:150,max:250,n:'Deeper Banuta',mon:'Hydra, Serpent Spawn, Medusa',xp:'alta',profit:'alto',diff:4,goal:'balance',req:'Banuta access; proteção e imbuements',tip:'Ótimo equilíbrio. Não trate como hunt de iniciante: posicionamento e tamanho da pull importam muito.'},
{min:250,max:400,n:'Glooth Tower / Carnivora’s Rock',mon:'Glooth Anemone, Glooth Bandit, Carnivora',xp:'alta',profit:'alto',diff:4,goal:'profit',req:'Set adequado + imbuements',tip:'Boa faixa para EK que quer dinheiro sem abandonar XP. Escolha a rota conforme seu equipamento.'},
{min:400,max:9999,n:'Soulwar — rota adequada ao seu set',mon:'Dark Throats, Rotten Golem e outros',xp:'muito alta',profit:'alto',diff:5,goal:'xp',req:'Acesso Soulwar + set forte',tip:'Conteúdo de alto risco. Aqui a recomendação depende bastante de skill, set, charms e experiência do jogador.'}],
Paladin:[
{min:8,max:25,n:'Rotworms / Swamp Trolls',mon:'Rotworm, Swamp Troll',xp:'baixa',profit:'baixo-médio',diff:1,goal:'safe',req:'Bow/weapon básica + munição',tip:'Mantenha distância e não desperdice munição. Ótimo começo para aprender kite.'},
{min:25,max:60,n:'Yalahar Elves / Coryms',mon:'Elf, Corym',xp:'média',profit:'médio',diff:2,goal:'balance',req:'Arma à distância adequada',tip:'Use corredores e distância a seu favor. Evite ficar cercado para não gastar mana/HP à toa.'},
{min:50,max:100,n:'Yielothax / Grimvale',mon:'Yielothax, Werecreature',xp:'média-alta',profit:'médio-alto',diff:3,goal:'balance',req:'Premium; imbuements ajudam',tip:'Boa progressão. Paladin ganha muito quando consegue manter distância e uma rota limpa.'},
{min:80,max:130,n:'Oramond West',mon:'Minotaur Amazon, Execowtioner',xp:'alta',profit:'alto',diff:3,goal:'profit',req:'Acesso Oramond',tip:'Excelente para dinheiro. Evite bloquear sua própria rota e planeje a saída antes da pull.'},
{min:120,max:200,n:'Werehyenas / Exotic Cave',mon:'Werehyena, Exotic Bat',xp:'alta',profit:'alto',diff:4,goal:'balance',req:'Acesso; set e imbuements',tip:'Ótima relação XP/profit para RP. Faça pulls que permitam reposicionamento constante.'},
{min:180,max:300,n:'Mirror / Glooth Tower',mon:'Dark Faun, Glooth',xp:'alta',profit:'alto',diff:4,goal:'profit',req:'Equipamento compatível',tip:'Priorize rota segura e controle de distância. Profit pode variar bastante com preços do mundo.'},
{min:300,max:500,n:'Prison — rota de Paladin',mon:'Magistratus, Invoker e companhia',xp:'muito alta',profit:'alto',diff:5,goal:'xp',req:'Acesso + set forte',tip:'Alta exigência mecânica. Se a hunt estiver consumindo muita potion, reduza a pull antes de tentar aumentar XP.'},
{min:500,max:9999,n:'Soulwar / conteúdo endgame de RP',mon:'criaturas de Soulwar',xp:'muito alta',profit:'alto',diff:5,goal:'xp',req:'Acesso e equipamento endgame',tip:'Recomendação de alto risco. A rota exata deve considerar sua arma, charms e experiência.'}],
Sorcerer:[
{min:8,max:30,n:'Tarantulas / Cyclops',mon:'Tarantula, Cyclops',xp:'baixa-média',profit:'baixo',diff:1,goal:'safe',req:'Runas/spells básicas',tip:'Evite tomar hit desnecessário. O ganho vem de manter distância e não parar a rotação.'},
{min:30,max:70,n:'Coryms / Mutated Humans',mon:'Corym, Mutated Human',xp:'média',profit:'médio',diff:2,goal:'balance',req:'Spells de área',tip:'Boa fase para começar a acelerar a XP com área sem entrar em conteúdo muito perigoso.'},
{min:50,max:100,n:'Darashia Dragon Lair / Mother of Scarabs',mon:'Dragon, Ancient Scarab',xp:'média-alta',profit:'médio',diff:3,goal:'balance',req:'Elemental damage e supplies',tip:'Escolha a rota conforme sua resistência e elementos disponíveis. Não fique preso em corredor sem saída.'},
{min:80,max:130,n:'Oramond West / Carlin Cults',mon:'Minotaur, Cults',xp:'alta',profit:'médio-alto',diff:3,goal:'xp',req:'Premium + spells/imbues',tip:'Excelente para acelerar level. Controle a densidade das criaturas e mantenha uma rota de fuga.'},
{min:130,max:220,n:'Yalahar Grim Reapers',mon:'Grim Reaper',xp:'muito alta',profit:'baixo-médio',diff:4,goal:'xp',req:'Acesso e domínio de kite',tip:'Foco em XP. É uma hunt em que posicionamento vale mais que simplesmente aumentar o tamanho da pull.'},
{min:180,max:300,n:'Buried Cathedral',mon:'Falcon/Grave-related creatures',xp:'alta',profit:'alto',diff:4,goal:'balance',req:'Acesso; proteção e imbuements',tip:'Boa opção para balancear XP e loot. Aprenda as salas antes de tentar otimizar a rota.'},
{min:300,max:500,n:'Winter/Summer Court',mon:'Faun, Arachnophobica e companhia',xp:'muito alta',profit:'alto',diff:5,goal:'xp',req:'Acesso + proteção elemental',tip:'Conteúdo de alta exigência. O elemento da hunt e sua resistência mudam bastante o desempenho.'},
{min:500,max:9999,n:'Soulwar — rota de MS',mon:'criaturas de Soulwar',xp:'muito alta',profit:'alto',diff:5,goal:'xp',req:'Acesso + equipamento endgame',tip:'Endgame. A recomendação final depende de sua arma, charms, imbuements e experiência.'}],
Druid:[
{min:8,max:30,n:'Tarantulas / Cyclops',mon:'Tarantula, Cyclops',xp:'baixa-média',profit:'baixo',diff:1,goal:'safe',req:'Spells básicas + mana sustain',tip:'Use distância e cura para reduzir waste. O objetivo aqui é ganhar ritmo sem risco.'},
{min:30,max:70,n:'Coryms / Mutated Humans',mon:'Corym, Mutated Human',xp:'média',profit:'médio',diff:2,goal:'balance',req:'Spells de área',tip:'Boa transição para AoE. Evite entrar em salas fechadas sem conhecer a saída.'},
{min:50,max:100,n:'Mother of Scarabs / Dragon Lair',mon:'Ancient Scarab, Dragon',xp:'média-alta',profit:'médio',diff:3,goal:'balance',req:'Proteção e dano elemental',tip:'Escolha o spot de acordo com a resistência elemental disponível e o tipo de criatura.'},
{min:80,max:130,n:'Oramond West / Carlin Cults',mon:'Minotaur, Cults',xp:'alta',profit:'médio-alto',diff:3,goal:'xp',req:'Premium + imbuements',tip:'Ótima faixa para acelerar XP. Use controle de área e mantenha uma rota de fuga.'},
{min:130,max:220,n:'Yalahar Grim Reapers',mon:'Grim Reaper',xp:'muito alta',profit:'baixo-médio',diff:4,goal:'xp',req:'Acesso + kite',tip:'Excelente para XP, mas punição por erro é alta. Evite ficar encurralado.'},
{min:180,max:300,n:'Buried Cathedral',mon:'criaturas da Cathedral',xp:'alta',profit:'alto',diff:4,goal:'balance',req:'Acesso + proteção',tip:'Boa relação entre XP e loot. Faça a rota de forma consistente antes de buscar recorde.'},
{min:300,max:500,n:'Winter/Summer Court',mon:'criaturas Fey',xp:'muito alta',profit:'alto',diff:5,goal:'xp',req:'Acesso + proteção elemental',tip:'Alta exigência. A escolha de elemento e resistência pesa bastante no resultado.'},
{min:500,max:9999,n:'Soulwar — rota de ED',mon:'criaturas de Soulwar',xp:'muito alta',profit:'alto',diff:5,goal:'xp',req:'Acesso + equipamento endgame',tip:'Endgame. Ajuste a rota aos seus charms, imbuements e experiência.'}],
Monk:[
{min:8,max:20,n:'Rotworms — Darashia/Liberty Bay',mon:'Rotworm, Carrion Worm',xp:'baixa',profit:'baixo',diff:1,goal:'safe',req:'Fist weapon básica',tip:'Começo seguro para aprender alcance e sustain do Monk. Não force AoE cedo demais.'},
{min:20,max:40,n:'Upper Spike / Chor',mon:'criaturas de Spike e Chor',xp:'média',profit:'baixo-médio',diff:2,goal:'balance',req:'Acesso e habilidades iniciais do Monk',tip:'Faixa em que o Monk começa a ganhar ritmo. Priorize pulls controladas e aprenda o timing das habilidades.'},
{min:40,max:60,n:'Banuta Apes / Darashia Dragons',mon:'Ape, Dragon',xp:'média-alta',profit:'alto',diff:3,goal:'profit',req:'Set compatível; acesso quando necessário',tip:'Banuta é boa para profit; Dragons podem acelerar XP. Escolha conforme seu objetivo e equipamento.'},
{min:60,max:100,n:'Yielothax / Grimvale / Carlin Cults',mon:'Yielothax, Werecreature, Cult',xp:'alta',profit:'médio-alto',diff:3,goal:'balance',req:'Acesso + Sai adequada',tip:'Faixa forte do Monk. Use sustain para reduzir downtime e não trate a cura como licença para puxar infinito.'},
{min:100,max:150,n:'Oramond West — Minos',mon:'Minotaur Amazon, Execowtioner',xp:'alta',profit:'alto',diff:3,goal:'profit',req:'Acesso Oramond',tip:'Spot muito interessante para Monk: boa combinação de XP e loot. Ajuste o tamanho da pull à sua defesa.'},
{min:130,max:220,n:'Yalahar Grim Reapers',mon:'Grim Reaper',xp:'muito alta',profit:'baixo',diff:4,goal:'xp',req:'Acesso + domínio de posicionamento',tip:'Foco em XP. É uma das referências atuais para Monk nessa faixa, mas erro de posicionamento é caro.'},
{min:150,max:270,n:'Deeper Banuta -6',mon:'Medusa, Serpent Spawn, Hydra, Giant Spider',xp:'muito alta',profit:'alto',diff:4,goal:'balance',req:'Banuta access',tip:'Excelente equilíbrio para Monk. A rota exige conhecimento e controle; não comece tentando maximizar a pull.'},
{min:200,max:330,n:'Pirats — The Wreckoning',mon:'Pirat Cutthroat, Mate, Bombardier, Scoundrel',xp:'alta',profit:'alto',diff:3,goal:'profit',req:'The Wreckoning access',tip:'Boa opção de profit com risco menor que vários spots endgame. Ótima quando o objetivo é financiar supplies.'},
{min:250,max:450,n:'Adaean Crystal Mines / Adaean Shore',mon:'criaturas de Isle of Ada',xp:'alta',profit:'alto',diff:4,goal:'balance',req:'Isle of Ada access',tip:'Conteúdo específico de Monk disponível no banco de hunts atual. Priorize conhecer o respawn antes de buscar eficiência.'},
{min:400,max:9999,n:'Conteúdo endgame de Monk',mon:'Soulwar e spawns de alto nível compatíveis',xp:'muito alta',profit:'alto',diff:5,goal:'xp',req:'Equipamento endgame + acesso',tip:'Aqui não existe uma única resposta. A escolha deve considerar arma, charms, skills, resistência e objetivo da sessão.'}]
};

function huntScore(h,l,goal){const mid=(h.min+h.max)/2,fit=l>=h.min&&l<=h.max?100:Math.max(0,100-Math.abs(l-mid)*0.55),goalBonus=h.goal===goal?25:(goal==='balance'&&h.goal==='profit'?12:0),safety=goal==='safe'?(6-h.diff)*12:0;return fit+goalBonus+safety}
function calcHunt(){const l=Math.max(8,Number(document.getElementById('huntLevel').value||8)),v=document.getElementById('huntVoc').value,goal=document.getElementById('huntGoal')?.value||'balance',boost=document.getElementById('creature')?.textContent||'boost do dia',all=huntData[v]||huntData.Knight;const ranked=all.map(h=>({...h,score:huntScore(h,l,goal)})).sort((a,b)=>b.score-a.score).slice(0,3);const labels={xp:'XP máxima',profit:'Profit',balance:'Equilíbrio XP + profit',safe:'Segurança'};document.getElementById('huntResult').innerHTML=`<div class="eyebrow">${esc(v)} · Level ${fmt(l)} · ${labels[goal]}</div><p><strong>Como ler:</strong> a primeira opção é a mais alinhada ao seu level e objetivo. As outras duas são alternativas próximas. <strong>${esc(boost)}</strong> aparece como bônus do dia, mas não é automaticamente tratado como hunt compatível.</p>${ranked.map((h,j)=>`<div class="hunt-card" style="margin:10px 0;padding:14px;border:1px solid var(--line,#333);border-radius:10px"><div><span class="tag">${j===0?'RECOMENDADA':j===1?'ALTERNATIVA':'ALTERNATIVA'}</span> <strong>${esc(h.n)}</strong></div><div class="small" style="margin-top:7px">Level indicado: <strong>${h.min}–${h.max}</strong> · Dificuldade: ${'★'.repeat(h.diff)}${'☆'.repeat(5-h.diff)}</div><div class="small">Criaturas: ${esc(h.mon)}</div><div class="small">XP: ${esc(h.xp)} · Loot/profit: ${esc(h.profit)}</div><div class="small">Requisitos: ${esc(h.req)}</div><p style="margin:8px 0 0"><strong>Dica:</strong> ${esc(h.tip)}</p></div>`).join('')}`}
if(document.getElementById('huntBtn'))document.getElementById('huntBtn').onclick=calcHunt;
if(typeof renderPickers==='function'){const oldPickers=renderPickers;renderPickers=function(){oldPickers();document.querySelectorAll('#pickers input').forEach(i=>i.addEventListener('change',()=>setTimeout(drawCompare,0)));setTimeout(drawCompare,0)}}
setTimeout(drawCompare,500);setTimeout(calcHunt,600);