const API='https://api.tibiadata.com/v4/guild/'+encodeURIComponent('Mal Upados');
let members=[],history={},deaths={},selected=[];
const fmt=n=>new Intl.NumberFormat('pt-BR').format(Math.round(n));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const xp=l=>Math.floor(50*(Number(l)**3-6*Number(l)**2+17*Number(l)-12)/3);
function deathRaw(v){let seen=new Set();function walk(x,d=0){if(x==null||d>8)return'';if(typeof x==='string'){let s=x.trim();if(/\d{4}[-/]\d{2}[-/]\d{2}/.test(s))return s;return''}if(typeof x==='number'&&x>1000000000){let t=x>10000000000?x:x*1000,q=new Date(t);return Number.isFinite(q.getTime())?q.toISOString():''}if(typeof x!=='object'||seen.has(x))return'';seen.add(x);for(const k of ['date','datetime','timestamp','time','death_date','created']){let r=walk(x[k],d+1);if(r)return r}for(const k of Object.keys(x)){let r=walk(x[k],d+1);if(r)return r}return''}return walk(v)}
function deathDate(v){let s=deathRaw(v);if(!s)return'Data indisponível';let m=s.match(/(\d{4})[-/](\d{2})[-/](\d{2})(?:[ T](\d{2}):(\d{2})(?::(\d{2}))?)?/);return m?`${m[3]}/${m[2]}/${m[1]}${m[4]?` ${m[4]}:${m[5]}${m[6]?':'+m[6]:''}`:''}`:'Data indisponível'}
function daysAgo(v){let s=deathRaw(v),t=s?Date.parse(s.replace(' ','T')):NaN;return Number.isFinite(t)?Math.floor((Date.now()-t)/86400000):99999}
function latestDeath(name){return(deaths[name]||[]).slice().sort((a,b)=>(Date.parse(deathRaw(b))||0)-(Date.parse(deathRaw(a))||0))[0]}
function renderAchievements(){let cards=[];let daily={};let ds=Object.keys(history).sort();for(let i=1;i<ds.length;i++){let p=history[ds[i-1]]||{},c=history[ds[i]]||{};for(let [n,l] of Object.entries(c)){let g=Math.max(0,xp(l)-xp(p[n]??l));if(g>0)daily[`${ds[i]}|${n}`]={name:n,date:ds[i],gain:g,from:p[n]??l,to:l}}}let best=Object.values(daily).sort((a,b)=>b.gain-a.gain)[0];if(best)cards.push(`<div class="card"><div class="eyebrow">Recordista</div><h3>${esc(best.name)}</h3><p>Maior XP equivalente em um dia: <strong class="xp">+${fmt(best.gain)} XP</strong>.</p><span class="small">${best.date} · ${best.from} → ${best.to}</span></div>`);let rat=Object.entries(deaths).flatMap(([name,list])=>list.map(d=>({name,d}))).find(x=>/\brat\b/i.test(`${x.d?.reason||''} ${x.d?.killer||''} ${x.d?.description||''}`));if(rat)cards.push(`<div class="card"><div class="eyebrow">Primeira vítima do rato</div><h3>${esc(rat.name)}</h3><p>Conquista desbloqueada: encontrou a morte mais clássica de Tibia.</p><span class="small">${deathDate(rat.d)}</span></div>`);let candidates=members.map(m=>({m,d:latestDeath(m.name)})).filter(x=>!x.d||daysAgo(x.d)>=30).sort((a,b)=>a.m.name.localeCompare(b.m.name));if(candidates.length)cards.push(`<div class="card"><div class="eyebrow">30 dias sem morrer</div><h3>${candidates.slice(0,3).map(x=>esc(x.m.name)).join(' · ')}</h3><p>${candidates.length} membro(s) estão há pelo menos 30 dias sem morte registrada.</p></div>`);let high=members.slice().sort((a,b)=>(b.level||0)-(a.level||0))[0];if(high)cards.push(`<div class="card"><div class="eyebrow">Topo atual</div><h3>${esc(high.name)}</h3><p>Maior level atual da guilda: <strong>${fmt(high.level)}</strong>.</p></div>`);document.getElementById('achievements').innerHTML=cards.join('')||'<div class="small">Ainda não há histórico suficiente para desbloquear conquistas.</div>'}
function renderFalls(){let rows=Object.entries(deaths).flatMap(([name,list])=>list.map(d=>({name,d,level:Number(d.level||members.find(m=>m.name===name)?.level||0),reason:d.reason||d.description||d.killer||'Causa não informada'})));let score=r=>{let s=r.reason.toLowerCase(),weak=/rat|spider|cave rat|snake|wolf|deer|bug|wasp/.test(s)?80:0;return weak+Math.min(50,r.level/20)};rows.sort((a,b)=>score(b)-score(a));document.getElementById('falls').innerHTML=rows.slice(0,12).map((x,i)=>`<tr><td class="rank">${i+1}</td><td><strong>${esc(x.name)}</strong></td><td>${fmt(x.level)}</td><td>${esc(x.reason)}</td><td>${deathDate(x.d)}</td></tr>`).join('')||'<tr><td colspan="5">Nenhuma morte retornada.</td></tr>'}
function renderRace(){let ds=Object.keys(history).sort(),start=ds[Math.max(0,ds.length-8)],end=ds.at(-1),rows=Object.entries(history[end]||{}).map(([name,l])=>({name,level:Number(l),gain:Math.max(0,xp(l)-xp((history[start]||{})[name]??l))})).sort((a,b)=>b.gain-a.gain).slice(0,8);document.getElementById('racePeriod').innerHTML=ds.length>1?`<strong>Janela:</strong> ${start} → ${end} · quem mais ganhou XP equivalente larga na frente.`:'Histórico insuficiente.';document.getElementById('race').innerHTML=rows.map((x,i)=>`<div class="card"><div class="eyebrow">${i+1}º colocado</div><h3>${esc(x.name)}</h3><p>Level ${fmt(x.level)} · <strong class="xp">+${fmt(x.gain)} XP</strong> equivalente.</p></div>`).join('')||'<div class="small">Sem evolução registrada.</div>'}
function renderPickers(){document.getElementById('pickers').innerHTML=members.map(m=>`<label><input type="checkbox" value="${esc(m.name)}">${esc(m.name)}</label>`).join('');document.querySelectorAll('#pickers input').forEach(i=>i.onchange=()=>{selected=[...document.querySelectorAll('#pickers input:checked')].map(x=>x.value).slice(0,4);if(selected.length>=4)document.querySelectorAll('#pickers input:not(:checked)').forEach(x=>x.disabled=true);else document.querySelectorAll('#pickers input').forEach(x=>x.disabled=false);drawCompare()})}
function drawCompare(){let c=document.getElementById('compareChart'),empty=document.getElementById('compareEmpty'),ctx=c.getContext('2d'),rect=c.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=Math.max(600,rect.width*dpr);c.height=300*dpr;ctx.scale(dpr,dpr);let W=Math.max(600,rect.width),H=300;ctx.clearRect(0,0,W,H);if(selected.length<2){empty.hidden=false;return}empty.hidden=true;let ds=Object.keys(history).sort(),pad=35;let vals=selected.map(n=>ds.map(d=>Number((history[d]||{})[n]||0)));let min=Math.min(...vals.flat().filter(Boolean)),max=Math.max(...vals.flat().filter(Boolean));if(!Number.isFinite(min)||max===min){empty.hidden=false;return}selected.forEach((n,idx)=>{let v=vals[idx];ctx.beginPath();v.forEach((l,i)=>{let x=pad+i/(ds.length-1)*(W-pad*1.3),y=H-pad-(l-min)/(max-min)*(H-pad*1.8);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle=['#d04b3e','#f0c45c','#70b77a','#8b79d9'][idx];ctx.lineWidth=3;ctx.stroke();ctx.fillStyle=ctx.strokeStyle;ctx.font='12px Inter';ctx.fillText(n,10,18+idx*18)});ctx.strokeStyle='#2b3037';ctx.beginPath();ctx.moveTo(pad,10);ctx.lineTo(pad,H-pad);ctx.lineTo(W-20,H-pad);ctx.stroke()}
const hunts={Knight:[['Exotic Cave','XP alta · profit médio'],['Carnivora’s Rock','XP média · profit alto'],['Asura Palace','XP muito alta · exige atenção']],Paladin:[['Werelions','XP alta · profit alto'],['Mirror Nightmare','XP alta · profit médio'],['Glooth Tower','XP média · profit alto']],Sorcerer:[['Buried Cathedral','XP alta · profit médio'],['Issavi Surface','XP alta · profit alto'],['Summer Court','XP muito alta · risco alto']],Druid:[['Buried Cathedral','XP alta · profit médio'],['Winter Court','XP muito alta · risco alto'],['Deathlings','XP alta · profit alto']]};
function calcHunt(){let l=Math.max(8,Number(document.getElementById('huntLevel').value||8)),v=document.getElementById('huntVoc').value,boost=document.getElementById('creature')?.textContent||'boost da API';let base=hunts[v]||hunts.Knight;let tier=l<150?0:l<300?1:2;document.getElementById('huntResult').innerHTML=`<div class="eyebrow">${esc(v)} · Level ${fmt(l)}</div><p>Prioridade do dia: <strong>${esc(boost)}</strong> como criatura boostada, se a rota for compatível com seu level.</p>`+base.map((h,i)=>`<div class="hunt-card"><span class="tag">${i===tier?'RECOMENDADA':'ALTERNATIVA'}</span><strong>${esc(h[0])}</strong><div class="small">${esc(h[1])}</div></div>`).join('')}
function renderProfiles(){document.getElementById('profiles').innerHTML=members.map(m=>{let ds=Object.keys(history).sort(),last=ds.at(-1),first=ds[0],g=Math.max(0,xp((history[last]||{})[m.name]||m.level)-xp((history[first]||{})[m.name]||m.level));return `<div class="profile-card" data-name="${esc(m.name)}"><h3>${esc(m.name)}</h3><div class="profile-meta">${esc(m.vocation||'—')} · Level ${fmt(m.level)} · ${m.status==='online'?'<span class="online">Online</span>':'Offline'}</div><div class="small">Evolução registrada: +${fmt(g)} XP equivalente</div></div>`}).join('')||'<div class="small">Nenhum membro.</div>';document.querySelectorAll('.profile-card').forEach(c=>c.onclick=()=>showProfile(c.dataset.name))}
function showProfile(name){let m=members.find(x=>x.name===name),ds=Object.keys(history).sort(),points=ds.map(d=>[d,Number((history[d]||{})[name]||m.level)]),list=(deaths[name]||[]).slice().sort((a,b)=>(Date.parse(deathRaw(b))||0)-(Date.parse(deathRaw(a))||0)).slice(0,8);let box=document.createElement('div');box.className='modal open';box.innerHTML=`<div class="modalbox"><button class="close">×</button><div class="eyebrow">Perfil completo</div><h2>${esc(name)}</h2><p>${esc(m.rank||'')} · ${esc(m.vocation||'')} · Level ${fmt(m.level)}</p><div class="panel"><strong>Timeline de level</strong><div class="small" style="margin-top:10px">${points.slice(-12).map(p=>`${p[0]} · Level ${fmt(p[1])}`).join('<br>')||'Sem histórico'}</div></div><div class="panel" style="margin-top:12px"><strong>Mortes</strong><div class="small" style="margin-top:10px">${list.map(d=>`${deathDate(d)} · ${esc(d.reason||d.description||d.killer||'Causa não informada')}`).join('<br>')||'Nenhuma morte retornada.'}</div></div></div>`;document.body.appendChild(box);box.onclick=e=>{if(e.target===box||e.target.classList.contains('close'))box.remove()}}
function renderMural(){let posts=JSON.parse(localStorage.getItem('malupados_resenha')||'[]');document.getElementById('mural').innerHTML=posts.slice().reverse().slice(0,30).map(p=>`<div class="post"><div class="post-head"><span class="post-name">${esc(p.name)}</span><span class="post-date">${new Date(p.date).toLocaleString('pt-BR')}</span></div><div class="post-body">${esc(p.text)}</div></div>`).join('')||'<div class="small">Ainda está quieto. Alguém precisa começar a resenha.</div>'}
document.getElementById('postResenha').onclick=()=>{let name=document.getElementById('resenhaNome').value.trim(),text=document.getElementById('resenhaTexto').value.trim();if(!name||!text)return;let posts=JSON.parse(localStorage.getItem('malupados_resenha')||'[]');posts.push({name,text,date:new Date().toISOString()});localStorage.setItem('malupados_resenha',JSON.stringify(posts.slice(-100)));document.getElementById('resenhaTexto').value='';renderMural()};
document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{document.body.classList.remove('theme-purple','theme-blood','theme-venom','theme-frost','theme-gold','theme-black');let t=b.dataset.theme;document.body.classList.add('theme-'+t);localStorage.setItem('malupados_theme',t)});let savedTheme=localStorage.getItem('malupados_theme');if(savedTheme)document.body.classList.add('theme-'+savedTheme);
document.getElementById('huntBtn').onclick=calcHunt;window.addEventListener('resize',drawCompare);
async function load(){try{let [gr,hr]=await Promise.all([fetch(API+'?'+Date.now()),fetch('historico.json?'+Date.now())]);let g=await gr.json();history=await hr.json();members=g.guild?.members||[];let stamp=new Date();document.getElementById('updated').innerHTML=`Dados consultados agora · <strong>${stamp.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</strong>`;await Promise.all(members.map(async m=>{try{let r=await fetch('https://api.tibiadata.com/v4/character/'+encodeURIComponent(m.name)+'?'+Date.now());let j=await r.json(),c=j.character||{};deaths[m.name]=Array.isArray(c.deaths)?c.deaths:[]}catch(e){deaths[m.name]=[]}}));renderAchievements();renderFalls();renderRace();renderPickers();renderProfiles();renderMural();calcHunt()}catch(e){document.getElementById('updated').textContent='Não foi possível atualizar os dados agora.'}}
load();
